#!/bin/bash

pass=$(makepasswd)
login=student$(( $RANDOM % 999 + 1 ))
echo "$(hostname) $login $pass" >> /var/run/sshd/acc.txt
useradd -p $pass -m -s /bin/bash $login
echo $login:$pass | chpasswd
chown root:root /run/sshd
chmod 711 /run/sshd
service ssh restart
chmod ugo+rwx /dev/ttyUSB*
tail -f /dev/null