version: "3" 
services:
  minicom_test1:
    build: .
    container_name: stand1
    hostname: stand1
    ports:
      - "2222:22"
    volumes:
      - ./stand:/opt/stand
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
#      - /dev/ttyUSB1:/dev/ttyUSB1
#      - /dev/ttyUSB2:/dev/ttyUSB2
#      - /dev/ttyUSB3:/dev/ttyUSB3
      - /dev/ttyUSB4:/dev/ttyUSB4
      - /dev/ttyUSB5:/dev/ttyUSB5
    command: 
      - /opt/stand/scripts/start.sh
  minicom_test2:
    build: .
    container_name: stand2
    hostname: stand2
    ports:
      - "2223:22"
    volumes:
      - ./stand:/opt/stand
    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyUSB2:/dev/ttyUSB2
      - /dev/ttyUSB3:/dev/ttyUSB3
#      - /dev/ttyUSB4:/dev/ttyUSB4
#      - /dev/ttyUSB5:/dev/ttyUSB5
    command: 
      - /opt/stand/scripts/start.sh