version: "3" 
services:
  minicom_test1:
    build: .
    hostname: docker1
    ports:
      - 2222:2222
    volumes:
      - /home/vika/docker-project:/var/run/sshd
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
#      - /dev/ttyUSB1:/dev/ttyUSB1
#      - /dev/ttyUSB2:/dev/ttyUSB2
#      - /dev/ttyUSB3:/dev/ttyUSB3
    command: 
      - /var/run/sshd/addusers
  minicom_test2:
    build: .
    hostname: docker2
    ports:
      - 2223:2222
    volumes:
      - /home/vika/docker-project:/var/run/sshd
    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
#      - /dev/ttyUSB2:/dev/ttyUSB2
#      - /dev/ttyUSB3:/dev/ttyUSB3
    command: 
      - /var/run/sshd/addusers